language: python
python:
  # - 2.7
  - 3.6
before_install:
  - sudo apt-get -qq update
  - make deps-ubuntu
install:
  - make deps-pip test-deps-pip
script:
  - make assets
  - export TESSDATA_PREFIX="/usr/share/tesseract-ocr/4.00/tessdata"; make test TESSDATA_PREFIX="/usr/share/tesseract-ocr/4.00/tessdata"
